spring.application.name=agriforecast-backend
spring.config.import=optional:classpath:application-secret.properties

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Jackson Configuration
spring.jackson.time-zone=Asia/Seoul

# KOSIS API (공개 파라미터)
kosis.cpi.org-id=101
kosis.cpi.tbl-id=DT_1J22112
kosis.cpi.itm-id=T+
kosis.cpi.obj-l1=T10
kosis.ppi.org-id=301
kosis.ppi.tbl-id=DT_404Y016
kosis.ppi.itm-id=13103134764999+
kosis.ppi.obj-l1=13102134764ACC_CD.*

# 가락시장 공공데이터 API (공개 ID)
garak.public-data.id=7043
